language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

sudo: false

addons:
  apt:
    packages:
      - hunspell

install:
  - pip install -e .
  - pip install -r dev_requirements.txt
  - pip install python-coveralls

branches:
  only:
    - master
    - test

script:
  - doit
  - py.test
  - coverage run `which py.test`

after_success:
  - coveralls


notifications:
  email:
    on_success: change
    on_failure: change
